### ISSUE TITLE
Error loading presets from

### ISSUE THREAD

**Issue by Cjhyyd** [if-ai/ComfyUI-IF_LLM#1]
Error loading presets from G:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_LLM\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x93 in position 198: illegal multibyte sequence

**Comment by if-ai** [comment]
I fix the gbk format I think should work now

**Comment by Cjhyyd** [comment]
> I fix the gbk format I think should work Okay, I'll try tomorrow

**Comment by Cjhyyd** [comment]
> I fix the gbk format I think should work now

It can be used normally now.
